Update branch2_seco-service-portal.yml

diff --git a/.github/workflows/branch2_seco-service-portal.yml b/.github/workflows/branch2_seco-service-portal.yml
--- a/.github/workflows/branch2_seco-service-portal.yml
+++ b/.github/workflows/branch2_seco-service-portal.yml
@@ -32,6 +32,16 @@ jobs:
         with:
           name: node-app
           path: .
+      
+      - name: Validate publish profile secret
+        run: |
+          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
+            echo "Publish profile secret is missing!"
+            exit 1
+          else
+            echo "Publish profile secret is set."
+          fi
+
 
   
 
